### ISSUE TITLE
Account: allow space metadata & template instance metadata

### ISSUE THREAD

**Issue by FabianKramm** [kiosk-sh/kiosk#32]
Currently it is not possible to predefine labels and annotations for spaces that will be created on demand by a certain account. The same problem holds true for template instances that are created by default on space creation.  

We think this is a very prominent use case (e.g. selecting namespaces for applying certain admission rules) and should be addressed. It is probably best to restructure the account schema for this:
```yaml
apiVersion: tenancy.kiosk.sh/v1alpha1
kind: Account
spec:
  space:
    clusterRole: ... (the old Account.spec.spaceClusterRole)
    limit: ... (the old Account.spec.spaceLimit)
    templateInstances: []TemplateInstance (the old Account.spec.spaceDefaultTemplates and Switch type from TemplateInstanceSpec to TemplateInstance (with metadata))
    spaceTemplate: Space (new)
```

This new schema would allow users to specify metadata for the created spaces and templateInstances. If several sets of annotations or labels should be allowed for a certain account, it is probably best to create two accounts for these users and change the needed set on space creation via the `Space.spec.account` property.
