### ISSUE TITLE
Is it possible to limit GPU usage with kiosk

### ISSUE THREAD

**Issue by allamand** [kiosk-sh/kiosk#69]
Hi,

I tried to limit the number of GPU allowed in my account, but this not seams to be taken into account

Here is my AccountQuota

```
apiVersion: config.kiosk.sh/v1alpha1
kind: AccountQuota
metadata:
  name: dev-account-quota
spec:
  account: dev-account
  quota:
    hard:
      pods: "8"
      limits.cpu: "8"
      limits.nvidia.com/gpu: 4
```

But It does not seams to find and add the actual gpu already used by my pods
